"""phase2 campaign engine

Revision ID: 0d0e908bfe22
Revises: 75f27766c294
Create Date: 2026-09-05 11:27:53.035752
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0d0e908bfe22'
down_revision: Union[str, None] = '75f27766c294'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('state', sa.Enum('draft', 'scheduled', 'active', 'paused', 'completed', 'archived', name='campaign_state'), nullable=False),
    sa.Column('test_mode', sa.Boolean(), nullable=False),
    sa.Column('approval_mode', sa.Enum('auto', 'manual', name='approval_mode'), nullable=False),
    sa.Column('channels', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_workspace_id'), 'campaigns', ['workspace_id'], unique=False)
    op.create_index('ix_campaigns_ws_state', 'campaigns', ['workspace_id', 'state'], unique=False)
    op.create_table('campaign_steps',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('campaign_id', sa.String(length=36), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('channel', sa.Enum('email', 'linkedin', 'whatsapp', name='channel'), nullable=False),
    sa.Column('delay_days', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=512), nullable=True),
    sa.Column('body_template', sa.Text(), nullable=True),
    sa.Column('ai_prompt', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'order_index', name='uq_campaign_step_order')
    )
    op.create_index(op.f('ix_campaign_steps_campaign_id'), 'campaign_steps', ['campaign_id'], unique=False)
    op.create_table('campaign_leads',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('campaign_id', sa.String(length=36), nullable=False),
    sa.Column('lead_id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('state', sa.Enum('pending', 'active', 'replied', 'bounced', 'failed', 'skipped', 'completed', name='campaign_lead_state'), nullable=False),
    sa.Column('current_step', sa.Integer(), nullable=False),
    sa.Column('next_action_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'lead_id', name='uq_campaign_lead')
    )
    op.create_index(op.f('ix_campaign_leads_campaign_id'), 'campaign_leads', ['campaign_id'], unique=False)
    op.create_index('ix_campaign_leads_due', 'campaign_leads', ['state', 'next_action_at'], unique=False)
    op.create_index(op.f('ix_campaign_leads_lead_id'), 'campaign_leads', ['lead_id'], unique=False)
    op.create_index(op.f('ix_campaign_leads_workspace_id'), 'campaign_leads', ['workspace_id'], unique=False)
    op.create_index('ix_campaign_leads_ws', 'campaign_leads', ['workspace_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('lead_id', sa.String(length=36), nullable=True),
    sa.Column('campaign_id', sa.String(length=36), nullable=True),
    sa.Column('campaign_lead_id', sa.String(length=36), nullable=True),
    sa.Column('step_id', sa.String(length=36), nullable=True),
    sa.Column('channel', postgresql.ENUM('email', 'linkedin', 'whatsapp', name='channel', create_type=False), nullable=False),
    sa.Column('direction', sa.Enum('outbound', 'inbound', name='message_direction'), nullable=False),
    sa.Column('status', sa.Enum('queued', 'sent', 'delivered', 'opened', 'replied', 'bounced', 'failed', 'simulated', name='message_status'), nullable=False),
    sa.Column('subject', sa.String(length=512), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('to_address', sa.String(length=320), nullable=True),
    sa.Column('provider_message_id', sa.String(length=255), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['campaign_lead_id'], ['campaign_leads.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['step_id'], ['campaign_steps.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_messages_lead', 'messages', ['lead_id'], unique=False)
    op.create_index(op.f('ix_messages_lead_id'), 'messages', ['lead_id'], unique=False)
    op.create_index(op.f('ix_messages_workspace_id'), 'messages', ['workspace_id'], unique=False)
    op.create_index('ix_messages_ws_created', 'messages', ['workspace_id', 'created_at'], unique=False)
    op.create_table('message_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('message_id', sa.String(length=36), nullable=True),
    sa.Column('type', sa.Enum('queued', 'sent', 'delivered', 'opened', 'replied', 'bounced', 'failed', 'blocked', name='message_event_type'), nullable=False),
    sa.Column('provenance', postgresql.ENUM('observed', 'estimated', 'unknown', name='provenance', create_type=False), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_message_events_msg', 'message_events', ['message_id'], unique=False)
    op.create_index(op.f('ix_message_events_workspace_id'), 'message_events', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_events_workspace_id'), table_name='message_events')
    op.drop_index('ix_message_events_msg', table_name='message_events')
    op.drop_table('message_events')
    op.drop_index('ix_messages_ws_created', table_name='messages')
    op.drop_index(op.f('ix_messages_workspace_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_lead_id'), table_name='messages')
    op.drop_index('ix_messages_lead', table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_campaign_leads_ws', table_name='campaign_leads')
    op.drop_index(op.f('ix_campaign_leads_workspace_id'), table_name='campaign_leads')
    op.drop_index(op.f('ix_campaign_leads_lead_id'), table_name='campaign_leads')
    op.drop_index('ix_campaign_leads_due', table_name='campaign_leads')
    op.drop_index(op.f('ix_campaign_leads_campaign_id'), table_name='campaign_leads')
    op.drop_table('campaign_leads')
    op.drop_index(op.f('ix_campaign_steps_campaign_id'), table_name='campaign_steps')
    op.drop_table('campaign_steps')
    op.drop_index('ix_campaigns_ws_state', table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_workspace_id'), table_name='campaigns')
    op.drop_table('campaigns')
    # ### end Alembic commands ###
