"""initial schema

Revision ID: 75f27766c294
Revises: 
Create Date: 2026-09-05 10:40:25.593645
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '75f27766c294'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('workspaces',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspaces_slug'), 'workspaces', ['slug'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=True),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.Enum('create', 'update', 'delete', 'login', 'signup', 'import_csv', 'merge', 'suppress', 'send_blocked', name='audit_action'), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=True),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_workspace_id'), 'audit_logs', ['workspace_id'], unique=False)
    op.create_index('ix_audit_ws_created', 'audit_logs', ['workspace_id', 'created_at'], unique=False)
    op.create_table('companies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=512), nullable=True),
    sa.Column('industry', sa.String(length=255), nullable=True),
    sa.Column('size', sa.String(length=64), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('linkedin_url', sa.String(length=512), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('enrichment', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_workspace_id'), 'companies', ['workspace_id'], unique=False)
    op.create_index('ix_companies_ws_domain', 'companies', ['workspace_id', 'domain'], unique=False)
    op.create_index('ix_companies_ws_name', 'companies', ['workspace_id', 'name'], unique=False)
    op.create_table('connected_accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.Enum('email', 'linkedin', 'whatsapp', name='connected_account_type'), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('disconnected', 'connected', 'error', name='connected_account_status'), nullable=False),
    sa.Column('encrypted_credentials', sa.Text(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_connected_accounts_workspace_id'), 'connected_accounts', ['workspace_id'], unique=False)
    op.create_table('lead_sources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_sources_workspace_id'), 'lead_sources', ['workspace_id'], unique=False)
    op.create_table('saved_filters',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('definition', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'owner_id', 'name', name='uq_saved_filter')
    )
    op.create_index(op.f('ix_saved_filters_workspace_id'), 'saved_filters', ['workspace_id'], unique=False)
    op.create_table('suppression_list',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('value', sa.String(length=320), nullable=False),
    sa.Column('reason', sa.Enum('unsubscribed', 'bounced', 'complained', 'manual', 'invalid', name='suppression_reason'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'channel', 'value', name='uq_suppression_entry')
    )
    op.create_index(op.f('ix_suppression_list_workspace_id'), 'suppression_list', ['workspace_id'], unique=False)
    op.create_index('ix_suppression_ws_value', 'suppression_list', ['workspace_id', 'value'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('color', sa.String(length=24), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'name', name='uq_tag_ws_name')
    )
    op.create_index(op.f('ix_tags_workspace_id'), 'tags', ['workspace_id'], unique=False)
    op.create_table('workspace_members',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.Enum('owner', 'admin', 'sales', 'viewer', name='workspace_role'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'user_id', name='uq_workspace_user')
    )
    op.create_index(op.f('ix_workspace_members_user_id'), 'workspace_members', ['user_id'], unique=False)
    op.create_index(op.f('ix_workspace_members_workspace_id'), 'workspace_members', ['workspace_id'], unique=False)
    op.create_table('leads',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=True),
    sa.Column('source_id', sa.String(length=36), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=120), nullable=True),
    sa.Column('last_name', sa.String(length=120), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('linkedin_url', sa.String(length=512), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('ai_qualification', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('email_provenance', sa.Enum('observed', 'estimated', 'unknown', name='provenance'), nullable=False),
    sa.Column('status', sa.Enum('new', 'enriched', 'qualified', 'contacted', 'replied', 'won', 'lost', 'disqualified', name='lead_status'), nullable=False),
    sa.Column('campaign_status', sa.Enum('none', 'queued', 'active', 'paused', 'completed', name='campaign_status'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('custom_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['lead_sources.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_company_id'), 'leads', ['company_id'], unique=False)
    op.create_index(op.f('ix_leads_status'), 'leads', ['status'], unique=False)
    op.create_index(op.f('ix_leads_workspace_id'), 'leads', ['workspace_id'], unique=False)
    op.create_index('ix_leads_ws_email', 'leads', ['workspace_id', 'email'], unique=False)
    op.create_index('ix_leads_ws_linkedin', 'leads', ['workspace_id', 'linkedin_url'], unique=False)
    op.create_index('ix_leads_ws_name_company', 'leads', ['workspace_id', 'full_name', 'company_id'], unique=False)
    op.create_index('ix_leads_ws_phone', 'leads', ['workspace_id', 'phone'], unique=False)
    op.create_index('ix_leads_ws_status', 'leads', ['workspace_id', 'status'], unique=False)
    op.create_table('lead_tags',
    sa.Column('lead_id', sa.String(length=36), nullable=False),
    sa.Column('tag_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('lead_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lead_tags')
    op.drop_index('ix_leads_ws_status', table_name='leads')
    op.drop_index('ix_leads_ws_phone', table_name='leads')
    op.drop_index('ix_leads_ws_name_company', table_name='leads')
    op.drop_index('ix_leads_ws_linkedin', table_name='leads')
    op.drop_index('ix_leads_ws_email', table_name='leads')
    op.drop_index(op.f('ix_leads_workspace_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_status'), table_name='leads')
    op.drop_index(op.f('ix_leads_company_id'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_workspace_members_workspace_id'), table_name='workspace_members')
    op.drop_index(op.f('ix_workspace_members_user_id'), table_name='workspace_members')
    op.drop_table('workspace_members')
    op.drop_index(op.f('ix_tags_workspace_id'), table_name='tags')
    op.drop_table('tags')
    op.drop_index('ix_suppression_ws_value', table_name='suppression_list')
    op.drop_index(op.f('ix_suppression_list_workspace_id'), table_name='suppression_list')
    op.drop_table('suppression_list')
    op.drop_index(op.f('ix_saved_filters_workspace_id'), table_name='saved_filters')
    op.drop_table('saved_filters')
    op.drop_index(op.f('ix_lead_sources_workspace_id'), table_name='lead_sources')
    op.drop_table('lead_sources')
    op.drop_index(op.f('ix_connected_accounts_workspace_id'), table_name='connected_accounts')
    op.drop_table('connected_accounts')
    op.drop_index('ix_companies_ws_name', table_name='companies')
    op.drop_index('ix_companies_ws_domain', table_name='companies')
    op.drop_index(op.f('ix_companies_workspace_id'), table_name='companies')
    op.drop_table('companies')
    op.drop_index('ix_audit_ws_created', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_workspace_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_workspaces_slug'), table_name='workspaces')
    op.drop_table('workspaces')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
